[UPD]Api Banco inter V1 para v2
erpbrasil/erpbrasil.bank.inter pull request #7
Opened 2023-07-05 19:37 UTC by pablomatoskmee

Migração dos serviços de boleto da V1 para V2.

2023-07-11 13:06 UTC, pablomatoskmee commented
@rvalyi @mileo @ygcarvalh

2023-07-17 19:28 UTC, ygcarvalh requested changes

2023-07-17 19:28 UTC, ygcarvalh commented on src/erpbrasil/bank/inter/api.py
> +            print("Sem resposta do serviço de OAuth, provavelmente estourou o limite de chamadas por minuto...")
Consegue melhorar essa mensagem de retorno?

2023-07-17 19:32 UTC, ygcarvalh requested changes

2023-07-17 19:32 UTC, ygcarvalh commented on src/erpbrasil/bank/inter/api.py
> +            exit(1)
Pode só dar um return sem nada

2023-07-20 17:42 UTC, pablomatoskmee commented on src/erpbrasil/bank/inter/api.py
> +            print("Sem resposta do serviço de OAuth, provavelmente estourou o limite de chamadas por minuto...")
Corrigido.

2023-07-20 17:42 UTC, pablomatoskmee commented on src/erpbrasil/bank/inter/api.py
> +            exit(1)
Corrigido.

2023-07-21 12:28 UTC, ygcarvalh approved these changes

2023-07-27 13:02 UTC, merged